---
title: "11-13_adolescents_100824"
author: "Bella moger"
date: "2024-10-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


rm(list=ls())

# Load Packages
```{r}
library(tidyverse)## Always load tidyverse
library(skimr) ## Used to summarize our dataframe
library(corrplot) ## correlograms
library(psycho) ## dprime
#install.packages("MatchIt")
library(MatchIt) ## Matching with caliper
```

#take previous data file created, and manually remove all faces that were used... load back in
```{r}

## Set path
path <- "/Users/bellamoger/Documents/GitHub/SPARK/11-15 faces/"

## Load in
stimuli.work <- read.csv(paste0(path, "notused_stimuli.csv")) 

# look at distributions
stimuli.work %>% 
  ggplot()+
  geom_density(aes(x = pct_endorsed_child, color = "pct_endorsed_child", fill = "pct_endorsed_child"), 
               alpha = 0.1, na.rm = TRUE) +
  labs(x = "Value", y = "Density", title = "Percent Endorsed") +
  theme_classic()

## Distribution of different d' memorability scores accross all images
stimuli.work %>% 
  ggplot()+
  geom_density(aes(x = general_dprime, 
                   color = "general_dprime", fill = "general_dprime"), 
               alpha = 0.1, na.rm = TRUE) +
  geom_density(aes(x = highconfidence_treshold_dprime, 
                   color = "highconfidence_treshold_dprime", fill = "highconfidence_treshold_dprime"), 
               alpha = 0.1, na.rm = TRUE) +
  geom_density(aes(x = highconfidence_subset_dprime, 
                   color = "highconfidence_subset_dprime", fill = "highconfidence_subset_dprime"), 
               alpha = 0.1, na.rm = TRUE) +
  labs(x = "d'", y = "Density", title = "Memorability (d')") +
  theme_classic()
```


#how many faces OLDER than 9-13? 
#check for >13 year olds (age_rating)
```{r}
summary(stimuli.work)
older <-subset(stimuli.work,age_rating>13)
```


# look at distributions
```{r}
older %>% 
  ggplot()+
  geom_density(aes(x = pct_endorsed_child, color = "pct_endorsed_child", fill = "pct_endorsed_child"), 
               alpha = 0.1, na.rm = TRUE) +
  labs(x = "Value", y = "Density", title = "Percent Endorsed") +
  theme_classic()

## Distribution of different d' memorability scores accross all images
stimuli.work %>% 
  ggplot()+
  geom_density(aes(x = general_dprime, 
                   color = "general_dprime", fill = "general_dprime"), 
               alpha = 0.1, na.rm = TRUE) +
  geom_density(aes(x = highconfidence_treshold_dprime, 
                   color = "highconfidence_treshold_dprime", fill = "highconfidence_treshold_dprime"), 
               alpha = 0.1, na.rm = TRUE) +
  geom_density(aes(x = highconfidence_subset_dprime, 
                   color = "highconfidence_subset_dprime", fill = "highconfidence_subset_dprime"), 
               alpha = 0.1, na.rm = TRUE) +
  labs(x = "d'", y = "Density", title = "Memorability (d')") +
  theme_classic()
```


# Filtering out memorability outliers
Remove anyone two standard deviations away on any of our d' scores. 
```{r}
## Filter: keep anything where difference from mean does not exceed 2 SDs
contenders <- stimuli.work %>%
  filter(general_dprime > 0) %>%  ## NEW
  filter(abs(general_dprime - mean(general_dprime)) <= 2 * sd(general_dprime),
         abs(highconfidence_treshold_dprime - mean(highconfidence_treshold_dprime)) <= 2 * sd(highconfidence_treshold_dprime),
         abs(highconfidence_subset_dprime - mean(highconfidence_subset_dprime)) <= 2 * sd(highconfidence_subset_dprime)) 


#I WANT TO DOWNLOAD THE "CONTENDERS"
write.csv(stimuli.work,"contenders.csv")

#location
getwd()

## How many of each are left? 
table(contenders$door_or_face)
sort(table(contenders$image_type), decreasing = TRUE)

## How many of each face? 
contenders %>% 
  filter(door_or_face == "face") %>% 
  group_by(type) %>% 
  summarise(n = n()) %>% 
  arrange(-n) %>% View()
```



#final # --> goal age range = 11-15 y/o






